ALTER TABLE note ALTER COLUMN title TYPE VARCHAR(300);
ALTER TABLE note ALTER COLUMN description TYPE VARCHAR(12000);
ALTER TABLE event ALTER COLUMN name TYPE VARCHAR(300);
ALTER TABLE event ALTER COLUMN description TYPE VARCHAR(4000);